#pragma once

#define ID_UNCONNECTED_PING 0x01
#define ID_UNCONNECTED_PING_OPEN_CONNECTIONS 0x02
#define ID_UNCONNECTED_PONG 0x1C
#define ID_OPEN_CONNECTION_REQUEST_ONE 0x05
#define ID_OPEN_CONNECTION_REPLY_ONE 0x06
#define ID_OPEN_CONNECTION_REQUEST_TWO 0x07
#define ID_OPEN_CONNECTION_REPLY_TWO 0x08
#define ID_INCOMPATIBLE_PROTOCOL_VERSION 0x19
#define ID_ACK 0xC0
#define ID_NACK 0xA0
#define ID_CONNECTED_PING 0x00
#define ID_CONNECTED_PONG 0x03
#define ID_CONNECTION_REQUEST 0x09
#define ID_CONNECTION_REQUEST_ACCEPTED 0x10
#define ID_NEW_INCOMING_CONNECTION 0x13
#define ID_DISCONNECT_NOTIFICATION 0x15